export const GET_POKEMONS = 'GET_POKEMONS';
export const GET_POKEMONS_BY_NAME = 'GET_POKEMONS_BY_NAME';
export const RESET_FILTER = 'RESET_FILTER';
export const GET_POKEMON_BY_ID = "GET_POKEMON_BY_ID";
export const ACTION_FILTER_TYPES = "ACTION_FILTER_TYPES";
export const ACTION_TYPE_ORDEN = "ACTION_TYPE_ORDEN" 
export const GET_ALL_TYPES = "GET_ALL_TYPES"
